### ISSUE TITLE
read byte is 0 && java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by davitz-** [majidgolshadi/Android-Download-Manager-Pro#14]
I have set up a longer link time, but there is still a problem 

[CDS]read byte is 0
java.net.SocketTimeoutException
at java.net.PlainSocketImpl.read(PlainSocketImpl.java:497)
at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:42)
at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:242)
at com.android.okio.Okio$2.read(Okio.java:113)
at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
at java.io.InputStream.read(InputStream.java:162)
at com.golshadi.majid.core.chunkWorker.AsyncWorker.run(AsyncWorker.java:64)

**Comment by majidgolshadi** [comment]
Would you please describe more?

**Comment by taimur97** [comment]
Yes I also saw this exception but I don't know why

**Comment by 460611929** [comment]
set connection timeout length

**Comment by ishuqi** [comment]
I have met the SocketTimeoutException too, below is the log
04-01 10:01:27.095: W/System.err(12152): java.net.SocketTimeoutException
04-01 10:01:27.095: W/System.err(12152):    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
04-01 10:01:27.095: W/System.err(12152):    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-01 10:01:27.095: W/System.err(12152):    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-01 10:01:27.095: W/System.err(12152):    at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
04-01 10:01:27.095: W/System.err(12152):    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
04-01 10:01:27.096: W/System.err(12152):    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
04-01 10:01:27.096: W/System.err(12152):    at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
04-01 10:01:27.096: W/System.err(12152):    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
04-01 10:01:27.096: W/System.err(12152):    at java.io.InputStream.read(InputStream.java:162)
04-01 10:01:27.096: W/System.err(12152):    at com.golshadi.majid.core.chunkWorker.AsyncWorker.run(AsyncWorker.java:64)

**Comment by lekeCoder** [comment]
edit connection.setConnectTimeout() in AsynWorker.java.

That should resolve that error
