### ISSUE TITLE
attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by oneenam** [majidgolshadi/Android-Download-Manager-Pro#9]
``` java
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/package_name/databases/com.doitflash.air.extension.downloadManagerPro
            at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
            at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1626)
            at com.golshadi.majid.database.ChunksDataSource.delete(ChunksDataSource.java:75)
            at com.golshadi.majid.core.chunkWorker.Moderator.reBuildIsDone(Moderator.java:193)
            at com.golshadi.majid.core.chunkWorker.Rebuilder.run(Rebuilder.java:69)
```

it happening only for low memory device...any idea...

**Comment by oneenam** [comment]
```
java.lang.NullPointerException
            at android.database.sqlite.SQLiteStatement.releaseAndUnlock(SQLiteStatement.java:290)
            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:96)
            at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1861)
            at com.golshadi.majid.database.ChunksDataSource.delete(ChunksDataSource.java:75)
            at com.golshadi.majid.core.chunkWorker.Moderator.reBuildIsDone(Moderator.java:193)
            at com.golshadi.majid.core.chunkWorker.Rebuilder.run(Rebuilder.java:69)
```

**Comment by majidgolshadi** [comment]
This error occur when you try to insert/update in db after close your database connection
